# Generated by Django 5.1.4 on 2025-01-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/profile_pictures/blank.jpg', upload_to='static/profile_pictures/students/'),
        ),
    ]
