# Generated by Django 5.1.4 on 2025-01-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pictures/blank.jpg', upload_to='profile_pictures/students/'),
        ),
    ]
