# Generated by Django 5.1.4 on 2025-01-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_student_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.CharField(default='Year 7', max_length=10),
        ),
    ]
