# Generated by Django 5.1.4 on 2025-01-06 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_faculty_profile_pic'),
        ('Students', '0007_remove_student_year_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.CharField(max_length=10, unique=True)),
                ('adviser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faculty.faculty')),
            ],
            options={
                'verbose_name': 'Year Level',
                'verbose_name_plural': 'Year Levels',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.yearlevel'),
        ),
    ]
