# Generated by Django 5.1.4 on 2025-01-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0005_alter_subjects_schedule'),
        ('Students', '0008_yearlevel_student_year_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YearLevel',
            new_name='Classes',
        ),
    ]
