# Generated by Django 5.1.4 on 2025-01-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_rename_yearlevel_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
