# Generated by Django 5.1.4 on 2025-01-07 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0005_alter_subjects_schedule'),
        ('Students', '0010_alter_classes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='adviser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faculty.faculty'),
        ),
    ]
