# Generated by Django 5.1.4 on 2025-01-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0012_grades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='subject_id',
            new_name='subject_code',
        ),
    ]
