# Generated by Django 5.1.4 on 2025-01-08 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0003_alter_parent_options'),
        ('Students', '0014_rename_student_id_grades_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Parents.parent'),
        ),
    ]
