# Generated by Django 5.1.4 on 2025-01-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.TextField()),
                ('log_type', models.TextField()),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
