# Generated by Django 5.1.4 on 2025-01-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0002_alter_useraccesslogs_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccesslogs',
            options={'verbose_name': 'User Access Log', 'verbose_name_plural': 'User Access Logs'},
        ),
        migrations.AlterField(
            model_name='useraccesslogs',
            name='log_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccesslogs',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccesslogs',
            name='user_type',
            field=models.CharField(max_length=50),
        ),
    ]
