# Generated by Django 5.1.4 on 2025-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0003_alter_useraccesslogs_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
                ('log_type', models.CharField(max_length=50)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Account Log',
                'verbose_name_plural': 'User Account Logs',
            },
        ),
        migrations.RenameField(
            model_name='useraccesslogs',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
