# Generated by Django 5.1.4 on 2025-01-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0010_lecturematerialslogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeChangesLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=50)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grade Changes Log',
                'verbose_name_plural': 'Grade Changes Logs',
            },
        ),
    ]
