# Generated by Django 5.1.2 on 2024-11-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_posts_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-date_posted',)},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
    ]
