# Generated by Django 5.1.2 on 2024-11-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_alter_posts_author_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-date_commented',)},
        ),
    ]
