# Generated by Django 5.1.4 on 2025-01-05 04:52

import Faculty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pictures/blank.jpg', upload_to=Faculty.models.profile_pic_path),
        ),
    ]
