# Generated by Django 5.1.4 on 2025-01-06 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_faculty_profile_pic'),
        ('Students', '0008_yearlevel_student_year_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Faculty.faculty')),
                ('year_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.yearlevel')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
