# Generated by Django 5.1.4 on 2025-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0003_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='schedule',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
