# Generated by Django 5.1.4 on 2025-01-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0004_subjects_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='schedule',
            field=models.TimeField(null=True),
        ),
    ]
