# Generated by Django 5.1.4 on 2025-01-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0007_alter_lecturematerial_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturematerial',
            options={'verbose_name': 'Lecture Material', 'verbose_name_plural': 'Lecture Materials'},
        ),
    ]
