# Generated by Django 5.1.4 on 2025-01-10 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0008_alter_lecturematerial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['faculty_id'], 'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculty'},
        ),
        migrations.AlterModelOptions(
            name='lecturematerial',
            options={'ordering': ['lecture_id'], 'verbose_name': 'Lecture Material', 'verbose_name_plural': 'Lecture Materials'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['subject_code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=20)),
                ('task_title', models.CharField(max_length=50)),
                ('task_description', models.TextField()),
                ('task_deadline', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.subjects')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['task_id'],
            },
        ),
    ]
