# Generated by Django 5.1.4 on 2025-01-08 06:56

import Faculty.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0005_alter_subjects_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=20)),
                ('lecture_title', models.CharField(max_length=50)),
                ('lecture_file', models.FileField(upload_to=Faculty.models.lecture_material_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx'])])),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Faculty.subjects')),
            ],
        ),
    ]
