# Generated by Django 5.1.4 on 2025-01-08 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0006_lecturematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturematerial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.subjects'),
        ),
    ]
