# Generated by Django 5.1.4 on 2025-01-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0009_alter_faculty_options_alter_lecturematerial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_deadline',
            field=models.DateField(),
        ),
    ]
