# Generated by Django 5.1.4 on 2025-01-05 05:39

import Parents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pictures/blank.jpg', upload_to=Parents.models.profile_pic_path),
        ),
    ]
