# Generated by Django 5.1.4 on 2025-01-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0002_parent_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
    ]
