# Generated by Django 5.1.4 on 2025-01-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parents', '0003_alter_parent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['parent_id'], 'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
    ]
