# Generated by Django 5.1.4 on 2025-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesslogs',
            name='user_id',
            field=models.TextField(),
        ),
    ]
