# Generated by Django 5.1.4 on 2025-01-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0005_rename_log_type_useraccesslogs_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountlogs',
            name='action_by',
            field=models.CharField(default='System', max_length=50),
            preserve_default=False,
        ),
    ]
