# Generated by Django 5.1.4 on 2025-01-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0007_remove_useraccountlogs_action_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsChangesLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subjects Changes Log',
                'verbose_name_plural': 'Subjects Changes Logs',
            },
        ),
    ]
