# Generated by Django 5.1.4 on 2025-01-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0009_classchangeslogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureMaterialsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lecture Materials Log',
                'verbose_name_plural': 'Lecture Materials Logs',
            },
        ),
    ]
