# Generated by Django 5.1.4 on 2025-01-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0012_announcements_taskchangeslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'ordering': ['announcement_date'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='taskchangeslog',
            options={'verbose_name': 'Task Changes Log', 'verbose_name_plural': 'Task Changes Logs'},
        ),
    ]
