# Generated by Django 5.1.4 on 2025-01-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.CharField(default='Grade 7', max_length=10),
        ),
    ]
