# Generated by Django 5.1.4 on 2025-01-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_alter_student_year_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_level',
        ),
    ]
