# Generated by Django 5.1.4 on 2025-01-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0005_alter_subjects_schedule'),
        ('Students', '0011_alter_classes_adviser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('student_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
                ('subject_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Faculty.subjects')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
    ]
