# Generated by Django 5.1.4 on 2025-01-08 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0013_rename_subject_id_grades_subject_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='grades',
            old_name='subject_code',
            new_name='subject',
        ),
    ]
