# Generated by Django 5.1.4 on 2025-01-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0015_student_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['year_level'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='grades',
            options={'ordering': ['student', 'subject'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
